include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    empty_statements: true
    no_duplicate_case_values: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Style rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    sort_child_properties_last: true

    # Package specific rules
    public_member_api_docs: true
    sort_pub_dependencies: true

