name: ios_typography
description: A Flutter package that provides SwiftUI-like text styles for Cupertino widgets
version: "1.0.0"
homepage: https://github.com/islamdidarmd/ios_typography
repository: https://github.com/islamdidarmd/ios_typography
issue_tracker: https://github.com/islamdidarmd/ios_typography/issues
documentation: https://github.com/islamdidarmd/ios_typography#readme
topics:
  - typography
  - ios
  - cupertino
  - text-styles

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false 